package com.g3.model;
// Generated 22 mars 2022, 21:03:36 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cycles generated by hbm2java
 */
@Entity
@Table(name = "cycles", catalog = "parrainage")
public class Cycles implements java.io.Serializable {

	private int idCycles;
	private String nomC;
	private String sigles;
	private Set niveauses = new HashSet(0);

	public Cycles() {
	}

	public Cycles(int idCycles) {
		this.idCycles = idCycles;
	}

	public Cycles(int idCycles, String nomC, String sigles, Set niveauses) {
		this.idCycles = idCycles;
		this.nomC = nomC;
		this.sigles = sigles;
		this.niveauses = niveauses;
	}

	@Id

	@Column(name = "ID_CYCLES", unique = true, nullable = false)
	public int getIdCycles() {
		return this.idCycles;
	}

	public void setIdCycles(int idCycles) {
		this.idCycles = idCycles;
	}

	@Column(name = "NOM_C")
	public String getNomC() {
		return this.nomC;
	}

	public void setNomC(String nomC) {
		this.nomC = nomC;
	}

	@Column(name = "SIGLES")
	public String getSigles() {
		return this.sigles;
	}

	public void setSigles(String sigles) {
		this.sigles = sigles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cycles")
	public Set getNiveauses() {
		return this.niveauses;
	}

	public void setNiveauses(Set niveauses) {
		this.niveauses = niveauses;
	}

}
