package com.g3.model;
// Generated 22 mars 2022, 21:03:36 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Parcours generated by hbm2java
 */
@Entity
@Table(name = "parcours", catalog = "parrainage")
public class Parcours implements java.io.Serializable {

	private int idP;
	private Etudiants etudiants;
	private Niveaus niveaus;
	private String anneeAcademique;

	public Parcours() {
	}

	public Parcours(int idP, Etudiants etudiants, Niveaus niveaus) {
		this.idP = idP;
		this.etudiants = etudiants;
		this.niveaus = niveaus;
	}

	public Parcours(int idP, Etudiants etudiants, Niveaus niveaus, String anneeAcademique) {
		this.idP = idP;
		this.etudiants = etudiants;
		this.niveaus = niveaus;
		this.anneeAcademique = anneeAcademique;
	}

	@Id

	@Column(name = "ID_P", unique = true, nullable = false)
	public int getIdP() {
		return this.idP;
	}

	public void setIdP(int idP) {
		this.idP = idP;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ETUD", nullable = false)
	public Etudiants getEtudiants() {
		return this.etudiants;
	}

	public void setEtudiants(Etudiants etudiants) {
		this.etudiants = etudiants;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_N", nullable = false)
	public Niveaus getNiveaus() {
		return this.niveaus;
	}

	public void setNiveaus(Niveaus niveaus) {
		this.niveaus = niveaus;
	}

	@Column(name = "ANNEE_ACADEMIQUE")
	public String getAnneeAcademique() {
		return this.anneeAcademique;
	}

	public void setAnneeAcademique(String anneeAcademique) {
		this.anneeAcademique = anneeAcademique;
	}

}
