package applicationView;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

import javafx.scene.control.MenuButton;

public class enregistrementEtudiantController implements Initializable {
	
	@FXML
	private TextField NomEtude;
	@FXML
	private TextField PrenomEtude;
	@FXML
	private TextField genreEtude;
	@FXML
	private TextField matriculeEtude;
	@FXML
	private Button btn_Enregistrer;
	@FXML
	private MenuButton menuFiliere;
	@FXML
	private MenuButton menuCycle;

	// Event Listener on TextField[#NomEtude].onAction
	@FXML
	public void openNomEtude(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#PrenomEtude].onAction
	@FXML
	public void openPrenomEtude(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#genreEtude].onAction
	@FXML
	public void opengenreEtude(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#matriculeEtude].onAction
	@FXML
	public void openmatriculeEtude(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btn_Enregistrer].onAction
	@FXML
	public void openEnregistrer(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuButton[#menuFiliere].onAction
	@FXML
	public void openmenuFiliere(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuButton[#menuCycle].onAction
	@FXML
	public void openmenuCycle(ActionEvent event) {
		// TODO Autogenerated
	}

	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
		
	}
	
}
