package applicationView;
import com.g3.dao.*;
import com.g3.model.*;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;
import javafx.scene.control.ComboBox;
import javafx.scene.control.TextField;

import java.net.URL;
import java.util.List;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

import javafx.scene.control.MenuButton;

public class enregistrementEtudiantController implements Initializable {
	
	@FXML
	private TextField NomEtude;
	@FXML
	private TextField PrenomEtude;
	@FXML
	private TextField genreEtude;
	@FXML
	private TextField matriculeEtude;
	@FXML
	private Button btn_Enregistrer;
	@FXML
	private ComboBox <Integer> menuFiliere;
	@FXML
	private ComboBox <Integer> menuCycle;

	// Event Listener on TextField[#NomEtude].onAction
	@FXML
	public void openNomEtude(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#PrenomEtude].onAction
	@FXML
	public void openPrenomEtude(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#genreEtude].onAction
	@FXML
	public void opengenreEtude(ActionEvent event) {
		// TODO Autogenerated
		
	}
	// Event Listener on TextField[#matriculeEtude].onAction
	@FXML
	public void openmatriculeEtude(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btn_Enregistrer].onAction
	@FXML
	public void openEnregistrer(ActionEvent event) {
		// TODO Autogenerated
		Etudiants hans = new Etudiants();
		EtudiantsDao hansDao = new EtudiantsDao();
		
		hans.setMatricule(matriculeEtude.getText());
		hans.setNoms(NomEtude.getText());
		hans.setPrenoms(PrenomEtude.getText());
		hans.setSexe(genreEtude.getText());

	
	}
	// Event Listener on MenuButton[#menuFiliere].onAction
	@FXML
	public void openmenuFiliere(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuButton[#menuCycle].onAction
	@FXML
	public void openmenuCycle(ActionEvent event) {
		// TODO Autogenerated
	}

	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
	
		
		
		FilieresDao hanDao = new FilieresDao();
	     
	     
	     CyclesDao haDao = new CyclesDao();
	     
		
	}
	
}
