package applicationView;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

public class parrainageController  implements Initializable{
	
	
	@FXML
	private Button idMIAGE;
	@FXML
	private Button idASSRI;
	@FXML
	private Button idSEA;
	@FXML
	private Button IdEEEA;

	// Event Listener on Button[#idMIAGE].onAction
	@FXML
	public void openMIAGE(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#idASSRI].onAction
	@FXML
	public void openASSRI(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#idSEA].onAction
	@FXML
	public void openSEA(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#IdEEEA].onAction
	@FXML
	public void openEEEA(ActionEvent event) {
		// TODO Autogenerated
	}
	

	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
		
	}
	
}
